apiVersion: v1
kind: Service
metadata:
  name: elevate-svc
spec:
  type: NodePort
  selector:
    app: elevate
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30007
